"""Project rules: the author's own choices, compiled and bounded.

Rules are the one place TextGrader reports a violation rather than an
observation.  They are therefore configuration, and configuration written by a
person or generated by an agent can be wrong in two ways this module has to
survive: a pattern that does not compile, and a pattern that compiles but takes
exponential time on real prose.

Both are handled once, at load, rather than by ``re.finditer`` deep inside the
run.  A bad pattern becomes a visible unavailable result naming the rule; a slow
one is cut off by the ``regex`` package's matching timeout where that package is
installed, and bounded by a scan cap where it is not.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Iterable, Mapping

from .optional import require

#: Without the ``regex`` package there is no matching timeout, so a
#: catastrophically backtracking pattern is bounded by input size instead.
FALLBACK_SCAN_LIMIT = 2_000_000


@dataclass
class CompiledRule:
    rule_id: str
    name: str
    pattern: Any = None
    engine: str = "re"
    timeout: float | None = None
    error: str | None = None

    def finditer(self, text: str) -> list[dict[str, Any]]:
        """Matches as plain dictionaries, or an empty list if the rule is bad."""

        if self.pattern is None:
            return []
        body = text
        truncated = False
        if self.engine == "re" and len(body) > FALLBACK_SCAN_LIMIT:
            body, truncated = body[:FALLBACK_SCAN_LIMIT], True
        try:
            if self.engine == "regex" and self.timeout:
                found = list(self.pattern.finditer(body, timeout=self.timeout))
            else:
                found = list(self.pattern.finditer(body))
        except Exception as exc:
            self.error = f"pattern failed while matching: {type(exc).__name__}: {exc}"
            return []
        hits = [{"match": match.group(0)[:200], "offset": match.start()} for match in found]
        if truncated:
            self.error = (f"pattern was applied to the first {FALLBACK_SCAN_LIMIT:,} "
                          f"characters only; install the 'regex' package for a matching "
                          f"timeout instead of a size cap")
        return hits


def compile_rule(rule_id: str, name: str, pattern: str, *, flags: str = "i",
                 engine: str = "auto", timeout: float | None = 2.0) -> CompiledRule:
    """Compile one user pattern, reporting failure instead of raising."""

    module, reason = (require("regex") if engine in ("auto", "regex") else (None, None))
    if module is None and engine == "regex":
        return CompiledRule(rule_id, name, error=reason or "the 'regex' package is required")
    use_regex = module is not None
    engine_name = "regex" if use_regex else "re"
    compiler = module if use_regex else re
    bits = 0
    for letter in flags or "":
        bits |= {"i": compiler.IGNORECASE, "m": compiler.MULTILINE,
                 "s": compiler.DOTALL, "x": compiler.VERBOSE}.get(letter, 0)
    try:
        compiled = compiler.compile(pattern, bits)
    except Exception as exc:
        return CompiledRule(rule_id, name, error=f"invalid pattern: {type(exc).__name__}: {exc}")
    return CompiledRule(rule_id, name, compiled, engine_name, timeout)


def compile_rules(rules: Mapping[str, Any], settings: Mapping[str, Any] | None = None
                  ) -> list[CompiledRule]:
    """Compile every configured banned phrase once, before any text is scanned."""

    settings = settings or {}
    engine = settings.get("engine", "auto")
    timeout = settings.get("timeout_seconds", 2.0)
    out: list[CompiledRule] = []
    for index, rule in enumerate(rules.get("banned_phrases", []) or []):
        if not isinstance(rule, Mapping):
            out.append(CompiledRule(f"banned_phrase_{index + 1}", f"Rule {index + 1}",
                                    error="each banned_phrases entry must be an object"))
            continue
        rule_id = str(rule.get("id", f"banned_phrase_{index + 1}"))
        out.append(compile_rule(rule_id, str(rule.get("name", rule_id)),
                                str(rule.get("pattern", "")),
                                flags=str(rule.get("flags", "i")),
                                engine=engine, timeout=timeout))
    return out
